<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./models/env/FightScene/FightScene.gltf --transform --output ./src/lib/assets/Models --types --shadows --simplify
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube001_5: THREE.Mesh
      Cube001_6: THREE.Mesh
      Cube006: THREE.Mesh
      main_Bridge_5: THREE.Mesh
      main_Bridge_6: THREE.Mesh
      main_Bridge_7: THREE.Mesh
      Metal_Circle: THREE.Mesh
      Side_Bridge_5: THREE.Mesh
      Side_Bridge_6: THREE.Mesh
      Cube001_5: THREE.Mesh
      Cube001_6: THREE.Mesh
      Cube006_1: THREE.Mesh
      main_Bridge_5: THREE.Mesh
      main_Bridge_6: THREE.Mesh
      main_Bridge_7: THREE.Mesh
      Metal_Circle_1: THREE.Mesh
      Side_Bridge_5: THREE.Mesh
      Side_Bridge_6: THREE.Mesh
      Cube001_5: THREE.Mesh
      Cube001_6: THREE.Mesh
      Cube006_2: THREE.Mesh
      main_Bridge_5: THREE.Mesh
      main_Bridge_6: THREE.Mesh
      main_Bridge_7: THREE.Mesh
      Metal_Circle_2: THREE.Mesh
      Side_Bridge_5: THREE.Mesh
      Side_Bridge_6: THREE.Mesh
      Cube001_5: THREE.Mesh
      Cube001_6: THREE.Mesh
      Cube006_3: THREE.Mesh
      main_Bridge_5: THREE.Mesh
      main_Bridge_6: THREE.Mesh
      main_Bridge_7: THREE.Mesh
      Metal_Circle_3: THREE.Mesh
      Side_Bridge_5: THREE.Mesh
      Side_Bridge_6: THREE.Mesh
      Cube001_5: THREE.Mesh
      Cube001_6: THREE.Mesh
      Cube006_4: THREE.Mesh
      main_Bridge_5: THREE.Mesh
      main_Bridge_6: THREE.Mesh
      main_Bridge_7: THREE.Mesh
      Metal_Circle_4: THREE.Mesh
      Side_Bridge_5: THREE.Mesh
      Side_Bridge_6: THREE.Mesh
      Plane: THREE.Mesh
    }
    materials: {
      M_stonebricks_04: THREE.MeshStandardMaterial
      Metal: THREE.MeshStandardMaterial
      BlackBG: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/FightScene-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane.geometry}
      material={gltf.materials.BlackBG}
      scale={25}
    />
    <T.Group rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 2]}>
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube006.geometry}
        material={gltf.materials.M_stonebricks_04}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[210.18, 100, 100]}
      />
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_7.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Metal_Circle.geometry}
        material={gltf.materials.Metal}
        position={[0, 1, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Group position={[0, 4.97, 3.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[210.18, 100, 100]}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
    </T.Group>
    <T.Group position={[0, 0, 20]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 2]}>
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube006_1.geometry}
        material={gltf.materials.M_stonebricks_04}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[210.18, 100, 100]}
      />
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_7.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Metal_Circle_1.geometry}
        material={gltf.materials.Metal}
        position={[0, 1, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Group position={[0, 4.97, 3.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[210.18, 100, 100]}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
    </T.Group>
    <T.Group position={[0, 0, 40]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 2]}>
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube006_2.geometry}
        material={gltf.materials.M_stonebricks_04}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[210.18, 100, 100]}
      />
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_7.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Metal_Circle_2.geometry}
        material={gltf.materials.Metal}
        position={[0, 1, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Group position={[0, 4.97, 3.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[210.18, 100, 100]}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
    </T.Group>
    <T.Group position={[0, 0, 60]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 2]}>
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube006_3.geometry}
        material={gltf.materials.M_stonebricks_04}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[210.18, 100, 100]}
      />
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_7.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Metal_Circle_3.geometry}
        material={gltf.materials.Metal}
        position={[0, 1, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Group position={[0, 4.97, 3.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[210.18, 100, 100]}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
    </T.Group>
    <T.Group position={[0, 0, 80]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 2]}>
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube001_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube006_4.geometry}
        material={gltf.materials.M_stonebricks_04}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[210.18, 100, 100]}
      />
      <T.Group position={[0, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.main_Bridge_7.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Metal_Circle_4.geometry}
        material={gltf.materials.Metal}
        position={[0, 1, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Group position={[0, 4.97, 3.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[210.18, 100, 100]}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_5.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Side_Bridge_6.geometry}
          material={gltf.materials.M_stonebricks_04}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
